# Generated by Django 5.2.5 on 2025-08-25 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveBigIntegerField(verbose_name='цена')),
                ('description', models.TextField(verbose_name='описание')),
                ('title', models.CharField(max_length=200, verbose_name='название')),
                ('year_of_issue', models.PositiveIntegerField(verbose_name='год выпуска')),
                ('characteristics', models.JSONField(verbose_name='характеристики')),
            ],
            options={
                'verbose_name': 'объявление',
                'verbose_name_plural': 'объявления',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(unique=True, verbose_name='название города')),
            ],
            options={
                'verbose_name': 'город',
                'verbose_name_plural': 'города',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='AdvertImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='advert_images', verbose_name='изображение')),
                ('advert_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advert_images', to='car_adverts.advert', verbose_name='объявление')),
            ],
            options={
                'verbose_name': 'изображение',
                'verbose_name_plural': 'изображения',
                'ordering': ('id',),
            },
        ),
        migrations.AddField(
            model_name='advert',
            name='city_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city_adverts', to='car_adverts.city', verbose_name='город'),
        ),
    ]
