# Generated by Django 5.2.5 on 2025-08-25 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_adverts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='alias',
            field=models.CharField(default='', verbose_name='url параметр'),
        ),
    ]
