# Generated by Django 5.2.5 on 2025-08-28 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_adverts', '0002_city_alias'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='publication_date',
            field=models.DateField(blank=True, null=True, verbose_name='дата публикации'),
        ),
    ]
