# Generated by Django 5.2.5 on 2025-09-01 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_adverts', '0004_alter_advert_characteristics_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advert',
            old_name='city_id',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='advertimage',
            old_name='advert_id',
            new_name='advert',
        ),
    ]
